### PR TITLE
S3 integration rebuild

### LINKED ISSUE #166: Implement error handling for s3-integration
**Aufgabe**

- [x] digiwf-spring-cloudstream-utils mit neuer digiwf-message lib ersetzen (siehe Doku custom-integration-service: https://github.com/it-at-m/digiwf-core/blob/epic/error-handling-and-refactoring-integrations-534/docs/src/integrations/guides/custom-integration-service.md)
- [x] Error Handling implementieren
- [x] Fachliche Fehler (BpmnErrors) werfen
- [x] Doku ergänzen, um fachlichen Fehler
- [x] Element Template mit Streaming TemplateV02 erstellen und bereitstellen
~~Beispielprozess erstellen~~

Beispiel: Example Integration https://github.com/it-at-m/digiwf-core/tree/epic/error-handling-and-refactoring-integrations-534/digiwf-integrations/digiwf-example-integration

Aktueller Code Branch epic/error-handling-and-refactoring-integrations https://github.com/it-at-m/digiwf-core/tree/epic/error-handling-and-refactoring-integrations-534

Zum Testen kann die Example Integration: https://github.com/it-at-m/digiwf-core/tree/dev/digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-client-example/src/main/java/io/muenchendigital/digiwf/s3/integration/example/client/controller mit Postman verwendet werden

### LINKED ISSUE #410: Setup authentication for S3 Integration for local development
**Describe the bug**

You have to start the s3 integration with the no-security profile locally otherwise you get 401 unauthorized errors.

**Additional context**

It may also be a good idea to refactor the security configuration to use something similar to the digiwf-engine (e.g. https://github.com/it-at-m/digiwf-core/blob/dev/digiwf-engine/digiwf-engine-service/src/main/java/io/muenchendigital/digiwf/shared/configuration/SecurityConfiguration.java).

### PR DESCRIPTION
**Pull request by zambrovski**
**Description**

- Refactoring of S3 integration (using hex architecture)
- Implement new style of BPMN Error Handling and Incident Handling
- Use of a new message library instead of old streaming library
- client and service uses SSO in local environment
- switch to new spring security OAuth2
- remove unneeded spring libraries (HATEOS, Data REST, HAL)

**Reference**

Issues #410 #166

### CODE REVIEW

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-client-example/src/main/java/io/muenchendigital/digiwf/s3/integration/example/client/controller/AllEndpointsUsageController.java [hunk 1]
```diff
@@ -17,46 +16,45 @@
...
-
+  private static final String LOG_DIVIDER = "------------";
+
+  private final ClientFileUsageController clientFileUsageController;
+
+  private final ClientFolderUsageController clientFolderUsageController;
+
+  @GetMapping("/all")
+  @ResponseStatus(HttpStatus.OK)
+  public void getFile() throws DocumentStorageException, DocumentStorageClientErrorException, DocumentStorageServerErrorException, IOException, PropertyNotSetException {
```
Comment (dominikhorn93) [inline digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-client-example/src/main/java/io/muenchendigital/digiwf/s3/integration/example/client/controller/AllEndpointsUsageController.java:29]: don't know if we really need the example client.
An integration test instead would be better I guess?

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/FileController.java [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+  @GetMapping
+  @Operation(description = "Creates a presigned URL to fetch the file specified in the parameter from the S3 storage")
+  public ResponseEntity<PresignedUrlDto> get(@RequestParam @NotEmpty @Size(max = FileData.LENGTH_PATH_TO_FILE) @FolderInFilePath final String pathToFile,
+                                             @RequestParam @NotNull @Min(FileData.MIN_EXPIRES_IN_MINUTES) final Integer expiresInMinutes) {
+    try {
+      log.info("Received a request for S3 presigned url to download a file");
+      final PresignedUrl fileResponse = this.fileOperations.getFile(pathToFile, expiresInMinutes);
+      final PresignedUrlDto presignedUrlDto = this.presignedUrlMapper.model2Dto(fileResponse);
+      return ResponseEntity.ok(presignedUrlDto);
+    } catch (final FileSystemAccessException exception) {
```
Comment (dominikhorn93) [inline digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/FileController.java:52]: What is your opinion about Exception Handler via Controller Advices?

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/FolderController.java [hunk 3]
```diff
@@ -28,16 +26,16 @@
...
 
-    private final FolderHandlingService folderHandlingService;
 
+    private final FolderOperationsInPort folderOperations;
     private final FilesInFolderMapper filesInFolderMapper;
 
     @DeleteMapping
     @Operation(description = "Deletes the folder specified in the parameter together with the corresponding database entry")
-    public ResponseEntity<Void> delete(@RequestParam @NotEmpty @Size(max = FileRepository.LENGTH_PATH_TO_FILE) final String pathToFolder) {
+    public ResponseEntity<Void> delete(@RequestParam @NotEmpty final String pathToFolder) {
```
Comment (dominikhorn93) [inline digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/FolderController.java:35]: We do not use this endpoint at the moment - but would not delete it. We would have to ask some other projects that are using this lib.

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/RestExceptionMapping.java [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+import io.muenchendigital.digiwf.s3.integration.application.port.in.FileExistenceException;
+import org.springframework.http.ResponseEntity;
+import org.springframework.web.bind.annotation.ControllerAdvice;
+import org.springframework.web.bind.annotation.ExceptionHandler;
+
+@ControllerAdvice
+public class RestExceptionMapping {
+
+  @ExceptionHandler
+  public ResponseEntity<String> handleFileExistenceException(FileExistenceException exception) {
```
Comment (dominikhorn93) [inline digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/RestExceptionMapping.java:13]: There I found one, what about the other exceptions?

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/CleanUpDatabaseFilesWithoutCorrespondingS3FolderUseCase.java [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+  private final S3Repository s3Repository;
+  private final FileRepository fileRepository;
+
+  /**
+   * Cronjob scheduled method that deletes all {@link File} entities in the database
+   * for which no corresponding file exists in the S3 storage.
+   * <p>
+   * The deletion is performed only if the file entity was created more than a month ago.
+   */
+  @Transactional
```
Comment (dominikhorn93) [inline digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/CleanUpDatabaseFilesWithoutCorrespondingS3FolderUseCase.java]: I put @Transactional always on the UseCase classes.

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/FileOperationsUseCase.java [hunk 6]
```diff
@@ -0,0 +1,290 @@
...
+   *
+   * @param paths            list of paths to files and/or folders
+   * @param action           http method for the presigned url
+   * @param expiresInMinutes presigned url expiration time
+   * @param endOfLife        the files endOfLife. May be null. If null, no end of life is set
+   * @return list of pre-signed urls.
+   * @throws FileSystemAccessException on S3 access errors.
+   * @throws FileExistenceException    if file doesn't exist.
+   */
+  public List<PresignedUrl> getPresignedUrls(final List<String> paths, final Method action, final int expiresInMinutes, LocalDate endOfLife) throws FileSystemAccessException, FileExistenceException {
```
Comment (dominikhorn93) [inline digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/FileOperationsUseCase.java]: private

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/FileOperationsUseCase.java [hunk 7]
```diff
@@ -0,0 +1,290 @@
...
+   *
+   * @param path             path to file or folder
+   * @param action           http method for the presigned url
+   * @param expiresInMinutes presigned url expiration time
+   * @param endOfLife        the files endOfLife. May be null. If null, no end of life is set
+   * @return list of pre-signed urls.
+   * @throws FileSystemAccessException on S3 access errors.
+   * @throws FileExistenceException    if file doesn't exist.
+   */
+  public List<PresignedUrl> getPresignedUrls(final String path, final Method action, final int expiresInMinutes, final LocalDate endOfLife) throws FileSystemAccessException, FileExistenceException {
```
Comment (dominikhorn93) [inline digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/FileOperationsUseCase.java]: private

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/FileOperationsUseCase.java [hunk 8]
```diff
@@ -0,0 +1,290 @@
...
+   * Get a single presigned url for the path
+   *
+   * @param path             path to file or folder
+   * @param action           http method for the presigned url
+   * @param expiresInMinutes presigned url expiration time
+   * @param endOfLife        the files endOfLife. May be null. If null, no end of life is set
+   * @return pre-signed url.
+   * @throws FileSystemAccessException on S3 access errors.
+   */
+  public PresignedUrl getPresignedUrl(final String path, final Method action, final int expiresInMinutes, final LocalDate endOfLife) throws FileSystemAccessException {
```
Comment (dominikhorn93) [inline digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/FileOperationsUseCase.java]: private

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/port/in/CleanUpExpiredFilesInPort.java [hunk 9]
```diff
@@ -0,0 +1,8 @@
+package io.muenchendigital.digiwf.s3.integration.application.port.in;
+
+import org.springframework.transaction.annotation.Transactional;
+
+public interface CleanUpExpiredFilesInPort {
+  @Transactional
```
Comment (dominikhorn93) [inline digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/application/port/in/CleanUpExpiredFilesInPort.java:6]: Why Transactional here and not on other In ports like `CleanUpUnusedFoldersInPort`

File: digiwf-libs/digiwf-spring-security/digiwf-spring-security-core/src/main/java/io/muenchendigital/digiwf/spring/security/SpringSecurityProperties.java [hunk 10]
```diff
@@ -0,0 +1,25 @@
...
+@ConfigurationProperties(prefix = "digiwf.security")
+@Data
+public class SpringSecurityProperties {
+  /**
+   * Name of the registration used in main security protection (as resource server).
+   */
+  private String clientRegistration = "keycloak";
+
+  private String[] permittedUrls = {
+      "/error", // allow the error page
```
Comment (dominikhorn93) [inline digiwf-libs/digiwf-spring-security/digiwf-spring-security-core/src/main/java/io/muenchendigital/digiwf/spring/security/SpringSecurityProperties.java:15]: Do we have swagger? Should it be available without auth or should it even be available in prod?

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-client-example/src/main/java/io/muenchendigital/digiwf/s3/integration/example/client/controller/AllEndpointsUsageController.java (hunk 1 above)
Comment (dominikhorn93) [reply digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-client-example/src/main/java/io/muenchendigital/digiwf/s3/integration/example/client/controller/AllEndpointsUsageController.java:29]: -> Future Story

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/FileController.java (hunk 2 above)
Comment (zambrovski) [reply digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/FileController.java:52]: We don't have a uniform mapping here. Therefor it will remain in controller.

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/FolderController.java (hunk 3 above)
Comment (zambrovski) [reply digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/FolderController.java:35]: Ok. No changes for the moment.

File: digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/RestExceptionMapping.java (hunk 4 above)
Comment (zambrovski) [reply digiwf-integrations/digiwf-s3-integration/digiwf-s3-integration-core/src/main/java/io/muenchendigital/digiwf/s3/integration/adapter/in/rest/RestExceptionMapping.java:13]: No uniform handling

File: digiwf-libs/digiwf-spring-security/digiwf-spring-security-core/src/main/java/io/muenchendigital/digiwf/spring/security/SpringSecurityProperties.java (hunk 10 above)
Comment (zambrovski) [reply digiwf-libs/digiwf-spring-security/digiwf-spring-security-core/src/main/java/io/muenchendigital/digiwf/spring/security/SpringSecurityProperties.java:15]: you still can override it via properties. For the moment I won't change this.
