### PR TITLE
chore(#965): fix compiler warnings

### LINKED ISSUE #965: Remove Mapstruct Warnings
Task wird noch ausformuliert von @StephanStrehlerCGI 

Warning: 
Unmapped target properties
TODO; 

 @Mapping(target = "startForm", ignore = true)
    @Mapping(target = "jsonSchema", ignore = true)

### PR DESCRIPTION
**Pull request by lmoesle**
### Description

Short description or comments

### Reference

Issues: closes #965

### Check-List

- [ ] All Acceptance criteria of user story are met
- [ ] JUnit tests are written (60% CodeCov)
- [ ] [Internal Review]([https://github.com/it-at-m/digiwf-core/blob/dev/CHANGELOG.md](https://confluence.muenchen.de/display/MPdZ/Review+-+DigiWF)) is maintained
- [ ] Documentations [external](https://github.com/it-at-m/digiwf-core/tree/dev/docs) and [internal](https://wiki.muenchen.de/betriebshandbuch/index.php?title=DigiWF&sfr=betriebshandbuch) are completed
- [ ] Smoketest successful (Manual E2E-Test depending on Change) 
- [ ] No Branch waste left
- [ ] [Board](https://app.zenhub.com/workspaces/digiwf-621f70bf50ea1100120b7e93/board) is up-to-date
- [ ] Openshift environments are prepared (Secrets, etc.) and release-issue is maintained

### CODE REVIEW

**Comment by lmoesle** [comment]
```
WARNING] The following options were not recognized by any processor: '[mapstruct.defaultComponentModel]'
```

Every module that does not use mapstruct shows this warning. We could fix it by removing the option from our root pom.xml and setting it only for modules that use mapstruct. But I would leave it like it is right now. Otherwhise we have to declare plugins for each module.

File: digiwf-engine/digiwf-engine-service/src/main/java/de/muenchen/oss/digiwf/humantask/api/resource/HumanTaskRestController.java [hunk 1]
```diff
@@ -4,23 +4,24 @@
...
-import jakarta.validation.Valid;
-
 
 /**
  * API for handle old process definition based tasks using new task service backend
  *
  * @deprecated
  * @author externer.dl.horn
  */
+@Deprecated
```
Comment (StephanStrehlerCGI) [inline digiwf-engine/digiwf-engine-service/src/main/java/de/muenchen/oss/digiwf/humantask/api/resource/HumanTaskRestController.java:24]: Wird die API nicht auch vom Taskservice verwendet?

**Review by StephanStrehlerCGI — APPROVED** [review]

File: digiwf-engine/digiwf-engine-service/src/main/java/de/muenchen/oss/digiwf/humantask/api/resource/HumanTaskRestController.java (hunk 1 above)
Comment (lmoesle) [reply digiwf-engine/digiwf-engine-service/src/main/java/de/muenchen/oss/digiwf/humantask/api/resource/HumanTaskRestController.java:24]: Glaube schon. Ich habe nur die fehlenden `@Deprecation` Anotations hinzugefügt.
